sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.stack
  - $HOME/.local/bin
  - $TRAVIS_BUILD_DIR/.stack-work

env: TRAVIS_TAG=0.19.0

matrix:
    include:
        - env: BUILD=linux
          compiler: ": #stack linux"
          language: generic
          addons: {apt: {packages: [libgmp-dev]}}
          deploy:
              provider: releases
              api_key:
                  secure: UKPF96hptHr4br4105TXKmi4v2N7H4toeRMOFAupwUi9Ilbrm+/2h6Cr+qc/2rrv63wQ0GyjhRe6Td8DKE26mDdSB/Ac5f9MQ8Ga519b6WFtPdnZ8g2i0Xc0foI4XsofYEwtLhdqUyfNNzT566najz+TC/RKqsWZaFk73VGoIUI=
              file: binary-for-linux.tar.gz
              draft: true
              skip_cleanup: true
              on:
                  all_branches: true

        - env: BUILD=mac
          compiler: ": #stack mac"
          language: generic
          os: osx
          deploy:
              provider: releases
              api_key:
                  secure: N+OIuVwMA9+2/7Xx/ObYGEa2oNiFv9PCdp+zLplfXpeAfhpoCbmnzPmBh1AlvzDH9743godTrarnbcTwLj+lFeTAtMfU/Y6U+1rl2lCYi5xDuV20Z+KG36m7T+nSkVvWDkHyFNdOQ89rnDrMF0Xc+5TZ0l7tVHzLUbD+/99OKck=
              file: binary-for-mac.tar.gz
              draft: true
              skip_cleanup: true
              on:
                  all_branches: true

        #- env: BUILD=win
        #  compiler: ": #stack windows"
        #  language: bash
        #  os: windows


before_install:
 - |
   set -ex
   case "$BUILD" in
       win)
           choco install haskell-stack
           ;;
       mac)
           travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
           ;;
       linux)
           travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
           ;;
   esac
   set +ex
    
install:
    - echo ">> trying only-dependencies $BUILD stack=$(which stack)"
    - stack --no-terminal --install-ghc build --only-dependencies

script:
    - echo ">> trying $BUILD stack=$(which stack)"
    - stack --no-terminal build
    - tar zcvf binary-for-$BUILD.tar.gz -C $(stack path --local-install-root)/bin .
    - echo ">> zipped? $(ls -1 *.tar.gz)"
    - echo ">> deploy tag $TRAVIS_TAG"

before_deploy:
    - git config --local user.name "Martin Mullins"
    - git config --local user.email "martin.mullins942@gmail.com"
    - export TRAVIS_TAG=0.19.0
    - git tag -f $TRAVIS_TAG
