sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

matrix:
    include:
        - env: BUILD=linux
          compiler: ": #stack linux"
          language: generic
          addons: {apt: {packages: [libgmp-dev]}}

        - env: BUILD=osx
          compiler: ": #stack osx"
          language: generic
          os: osx

        - env: BUILD=win
          compiler: ": #stack windows"
          language: bash
          os: windows


install:
    - echo ">> trying $BUILD"
    - if [[ -x $(which uname) ]]; then uname -r; else echo "no uname"; fi

script:
    - echo "test? $BUILD"
