sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.stack
  - $HOME/.local/bin
  - $TRAVIS_BUILD_DIR/.stack-work

matrix:
    include:
        - env: BUILD=linux
          compiler: ": #stack linux"
          language: generic
          addons: {apt: {packages: [libgmp-dev]}}

        - env: BUILD=osx
          compiler: ": #stack osx"
          language: generic
          os: osx

        - env: BUILD=win
          compiler: ": #stack windows"
          language: bash
          os: windows


before_install:
 - |
   set -ex
   case "$BUILD" in
       win)
           choco install haskell-stack
           ;;
       osx)
           travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
           ;;
       linux)
           travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
           ;;
   esac
   set +ex
    
install:
    - echo ">> trying only-dependencies $BUILD stack=$(which stack)"
    - stack --no-terminal --install-ghc build --only-dependencies

script:
    - echo ">> trying $BUILD stack=$(which stack)"
    - stack --no-terminal build
